# An unique identifier for the head node and workers of this cluster.
cluster_name: default

# The maximum number of workers nodes to launch in addition to the head
# node.
max_workers: 6

upscaling_speed: 1.0

# This executes all commands on all nodes in the docker container,
# and opens all the necessary ports to support the Ray cluster.
# Empty string means disabled.
docker:
    # image: rayproject/ray-ml:latest-gpu # You can change this to latest-cpu if you don't need GPU support and want a faster startup
    # image: rayproject/ray-ml:latest-cpu   # use this one if you don't need ML dependencies, it's faster to pull
    image: rayproject/ray:latest-py312-gpu # ray-ml was deprecated in 2024, use ray images instead
    container_name: "ray_container"
    pull_before_run: False # Changed to False to prevent re-checking every 5 seconds
    # If true, pulls latest version of image. Otherwise, `docker run` will only pull the image
    # if no cached version is present.
    # pull_before_run: True
    run_options:   # Extra options to pass into "docker run"
        - --ulimit nofile=65536:65536
        #- --shm-size=13gb # The configured object store size must not exceed /dev/shm size


# If a node is idle for this many minutes, it will be removed.
idle_timeout_minutes: 5

# Cloud-provider specific configuration.
provider:
    type: aws
    region: us-west-2
    # Availability zone(s), comma-separated, that nodes may be launched in.
    # Nodes will be launched in the first listed availability zone and will
    # be tried in the subsequent availability zones if launching fails.
    availability_zone: us-west-2a,us-west-2b
    # Whether to allow node reuse. If set to False, nodes will be terminated
    # instead of stopped.
    cache_stopped_nodes: False # If not present, the default is True.
    security_group:
        GroupName: ray_client_security_group
        IpPermissions:
              - FromPort: 10001
                ToPort: 10001
                IpProtocol: TCP
                IpRanges:
                    # Allow traffic only from your local IP address.
                    - CidrIp: 68.129.253.193/32

# How Ray will authenticate with newly launched nodes.
auth:
    ssh_user: ubuntu

available_node_types:
    ray.head.default:
        resources: {"head_node": 1}
        node_config:
            InstanceType: m5.large
            ImageId: ami-0387d929287ab193e
            # custom profile required to add "passRole" permission, which grants a custom role the worker nodes
            IamInstanceProfile:
                Arn: arn:aws:iam::<ACCOUNT-ID>:instance-profile/RayHeadProfile
            # You can provision additional disk space with a conf as follows
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 200
                      VolumeType: gp3
            # Additional options in the boto docs.
    ray.worker.expert:
        min_workers: 1
        max_workers: 4
        resources: {"expert-resource": 1}
        node_config:
            InstanceType: m5.xlarge
            ImageId: ami-0387d929287ab193e
            IamInstanceProfile:
                Arn: arn:aws:iam::<ACCOUNT-ID>:instance-profile/RayWorkerS3Profile
            InstanceMarketOptions:
                MarketType: spot
                # Additional options can be found in the boto docs, e.g.
                # SpotOptions:
                #     MaxPrice: 0.2
            # Additional options in the boto docs.
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 200 # must be >= 140
                      VolumeType: gp3
    ray.worker.default:
        min_workers: 1
        max_workers: 2
        resources: {"shared-resource": 1}
        node_config:
            InstanceType: m5.xlarge
            ImageId: ami-0387d929287ab193e
            # add iam role to access s3 bucket (read parquet file & teacher weights, write model checkpoints)
            IamInstanceProfile:
                Arn: arn:aws:iam::<ACCOUNT-ID>:instance-profile/RayWorkerS3Profile
            InstanceMarketOptions:
                MarketType: spot
                # Additional options can be found in the boto docs, e.g.
                # SpotOptions:
                #     MaxPrice: 0.2
            # Additional options in the boto docs.
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 200 # must be >= 140
                      VolumeType: gp3

# Specify the node type of the head node (as configured above).
head_node_type: ray.head.default

# Files or directories to copy to the head and worker nodes. The format is a
# dictionary from REMOTE_PATH: LOCAL_PATH, e.g.
file_mounts: {}

cluster_synced_files: []

# Whether changes to directories in file_mounts or cluster_synced_files in the head node
# should sync to the worker node continuously
file_mounts_sync_continuously: False

# Patterns for files to exclude when running rsync up or rsync down
rsync_exclude:
    - "**/.git"
    - "**/.git/**"

# Pattern files to use for filtering out files when running rsync up or rsync down. The file is searched for
# in the source directory and recursively through all subdirectories. For example, if .gitignore is provided
# as a value, the behavior will match git's behavior for finding and using .gitignore files.
rsync_filter:
    - ".gitignore"

# List of commands that will be run before `setup_commands`. If docker is
# enabled, these commands will run outside the container and before docker
# is setup.
initialization_commands: []

# List of shell commands to run to set up nodes.
setup_commands: []
# Custom commands that will be run on the head node after common setup.
head_setup_commands: []

# Custom commands that will be run on worker nodes after common setup.
worker_setup_commands: []

# Command to start ray on the head node. You don't need to change this.
# update default object-store-memory - lowering head object store helps memory pressure, but not enough
# use head as control-plane only by making processes unschedulable with num-cpu=0
head_start_ray_commands:
    - ray stop
    - ray start --head --port=6379 --object-manager-port=8076 --autoscaling-config=~/ray_bootstrap_config.yaml --dashboard-host=0.0.0.0
    # - ray start --head --port=6379 --object-manager-port=8076 --num-cpus=0 --object-store-memory=3221225472 --autoscaling-config=~/ray_bootstrap_config.yaml --dashboard-host=0.0.0.0

# Command to start ray on worker nodes. You don't need to change this.
# Add the custom resource label to force all the work to be scheduled to the worker nodes and avoid OOM on the head node
# this tag must be specified in the python function where the tasks are defined
worker_start_ray_commands:
    - ray stop
    # - ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076 --object-store-memory=9884901888
    - ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076 --labels="worker-label=True"
    # - ray start --address=$RAY_HEAD_IP:6379 --object-manager-port=8076 --object-store-memory=12884901888
